AleoHQ/snarkVM

Cargo.lock
derives/Cargo.toml
derives/src/lib.rs

This PR adds the `test_with_metrics` macros initially featured in SnarkOS. This change fell through the cracks when the split was undertaken. 
Another PR (AleoHQ/SnarkOS#582) will be ready to go in SnarkOS to point the `metrics` crate to the SnarkVM `derives` as the new dependency once this is merged (commit hash will be needed to make sure the dependency is up to date).

feat(derives): add test with metrics

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/ci.yml
Cargo.toml
dpc/src/base_dpc/mod.rs
dpc/src/base_dpc/parameters.rs
errors/src/dpc/dpc.rs
errors/src/parameters/parameters.rs
models/src/dpc/dpc.rs
models/src/dpc/dpc_components.rs
models/src/parameters/parameters.rs
parameters/src/params.rs
storage/src/error.rs
storage/src/ledger.rs
testing/src/dpc/mod.rs

Refactors parameters, modularizes DPC

Refactors parameters, modularizes DPC

---

algorithms/src/snark/gm17/mod.rs
algorithms/src/snark/gm17/prover.rs
algorithms/src/snark/gm17/tests.rs
algorithms/src/snark/groth16/mod.rs
algorithms/src/snark/groth16/prover.rs
algorithms/src/snark/groth16/tests.rs
errors/src/serialization/serialization.rs
gadgets/src/algorithms/snark/gm17.rs
gadgets/src/algorithms/snark/groth16.rs

The `groth16` and `gm17` proof serialization is now compressed by default using the `CanonicalSerialize` and `CanonicalDeserialize` form. This will significantly reduce the size of transactions, as the transaction proofs sizes are cut in half.
The uncompressed serialization of the proofs is still supported for backwards compatibility in the network.
Tests have been added to test that proof serialization is valid and the serialization format (compressed or uncompressed) is preserved.

Implements compressed Groth16 and GM17 proof serialization

---

Cargo.lock
Cargo.toml
dpc/Cargo.toml
errors/Cargo.toml
parameters/Cargo.toml
snarkvm/Cargo.toml
testing/Cargo.toml

A maintenance pass pruning unused dependencies.
In addition, the workspace-level `Cargo.toml` is simplified to only contain member information and the binary dependencies were moved to a new `Cargo.toml` under `snarkvm`.
These changes will also have a positive impact on `snarkOS` compilation times.

Remove unused dependencies

---

Cargo.lock
algorithms/Cargo.toml
algorithms/src/commitment/blake2s.rs
algorithms/src/prf/blake2s.rs
curves/Cargo.toml
dpc/Cargo.toml
dpc/src/base_dpc/transaction.rs
gadgets/Cargo.toml
gadgets/src/algorithms/merkle_tree/tests.rs
gadgets/src/algorithms/prf/tests.rs
marlin/Cargo.toml
models/Cargo.toml
models/benches/integer_arithmetic.rs
models/src/gadgets/utilities/uint/tests/uint128.rs
models/src/gadgets/utilities/uint/tests/uint16.rs
models/src/gadgets/utilities/uint/tests/uint32.rs
models/src/gadgets/utilities/uint/tests/uint64.rs
models/src/gadgets/utilities/uint/tests/uint8.rs
objects/Cargo.toml
parameters/Cargo.toml
polycommit/Cargo.toml
storage/Cargo.toml
testing/Cargo.toml
utilities/Cargo.toml

This update will also allow for the same to be done for `snarkos`.
`cargo update` was also run to auto-update some other dependencies.
Obviates https://github.com/AleoHQ/snarkVM/pull/39, https://github.com/AleoHQ/snarkVM/pull/18, https://github.com/AleoHQ/snarkVM/pull/10, https://github.com/AleoHQ/snarkVM/pull/3, https://github.com/AleoHQ/snarkVM/pull/19, and https://github.com/AleoHQ/snarkVM/pull/40.

Update rand to 0.8, blake2 and digest to 0.9

---

models/src/gadgets/r1cs/test_constraint_system.rs
models/src/gadgets/utilities/mod.rs
models/src/gadgets/utilities/optional_vec.rs

As the title states, this PR exposes the `OptionalVec` object used for optimization purposes, so that it can be utilized by the other projects that also use the `ConstraintSystem<F>` trait and can benefit from similar optimizations, like Leo.

Expose the OptionalVec helper object

---

models/src/curves/group.rs
models/src/dpc/dpc_components.rs
models/src/gadgets/r1cs/test_constraint_system.rs
models/src/gadgets/utilities/bits/rca.rs
models/src/gadgets/utilities/bits/sign_extend.rs
models/src/gadgets/utilities/int/arithmetic/div.rs
models/src/gadgets/utilities/int/arithmetic/mod.rs
models/src/gadgets/utilities/int/arithmetic/mul.rs
models/src/gadgets/utilities/int/arithmetic/neg.rs
models/src/gadgets/utilities/int/arithmetic/pow.rs
models/src/gadgets/utilities/int/arithmetic/sub.rs
models/src/gadgets/utilities/int/int_impl.rs
models/src/gadgets/utilities/int/relational/cmp.rs
models/src/gadgets/utilities/int/relational/eq.rs
models/src/gadgets/utilities/int/relational/mod.rs
models/src/gadgets/utilities/int/tests/int128.rs
models/src/gadgets/utilities/int/tests/int16.rs
models/src/gadgets/utilities/int/tests/int32.rs
models/src/gadgets/utilities/int/tests/int8.rs
models/src/gadgets/utilities/int/tests/mod.rs
models/src/gadgets/utilities/int/utilities/alloc.rs
models/src/gadgets/utilities/int/utilities/eq.rs
models/src/gadgets/utilities/int/utilities/mod.rs
models/src/gadgets/utilities/int/utilities/select.rs
utilities/Cargo.toml

* Move leo-gadgets last bits into snarkVM
* Add `to_bits_le`/`from_bits_le` methods for signed ints to mirror unsigned ints.
Copies tests verbatim from `leo-gadgets`

Signed Ints

---

r1cs/src/errors/synthesis.rs

The current `Display` impl for `SynthesisError` causes a stack overflow whenever the `else` branch is entered, due to using `{}` (which calls the `Display` impl for `SynthesisError`) within `write!`.
Fixes https://github.com/AleoHQ/leo/issues/666.

fix: avoid a stack overflow in the Display impl for SynthesisError

---

algorithms/src/fft/domain.rs
algorithms/src/fft/tests.rs
curves/benches/bls12_377/pairing.rs
curves/benches/bw6_761/pairing.rs
curves/benches/curves.rs
curves/src/traits/pairing_engine.rs
dpc/src/base_dpc/tests.rs
dpc/src/traits/program.rs
fields/src/primefield.rs
gadgets/src/algorithms/snark/groth16.rs
gadgets/src/fields/fp.rs
marlin/src/lib.rs
polycommit/src/kzg10/mod.rs
polycommit/src/lib.rs
polycommit/src/marlin_pc/mod.rs
storage/src/ledger.rs
storage/src/objects/dpc_state.rs
storage/src/objects/records.rs
storage/src/storage.rs

These changes make `cargo clippy --workspace --all-targets` with Rust 1.50 green.

1.50 clippy lints

---

derives/src/lib.rs
gadgets/src/traits/utilities/boolean.rs
nonnative/tests/arithmetic_tests.rs
objects/src/traits/storage.rs
posw/benches/posw.rs
posw/src/lib.rs

It seems that a few lints slipped through the cracks with the last pass; this time the `cargo clippy --workspace --all-targets` run was performed after `cargo clean`.

clippy: a few 1.50 lints more

---

gadgets/Cargo.toml

Those features are already used within the crate, so it doesn't impact the size of the lockfile. It's only a `dev-dependency`, too.

Enable default features in gadgets' rand dep to fix the benches

---

gadgets/src/traits/utilities/arithmetic/mul.rs
gadgets/src/traits/utilities/int/arithmetic/mul.rs
gadgets/src/traits/utilities/int/arithmetic/pow.rs
gadgets/src/traits/utilities/int/tests/int16.rs
gadgets/src/traits/utilities/int/tests/int32.rs
gadgets/src/traits/utilities/int/tests/int64.rs
gadgets/src/traits/utilities/int/tests/int8.rs

As discussed in https://github.com/AleoHQ/leo/pull/762 and outlined in https://github.com/AleoHQ/leo/issues/763, leo will be removing its `gadgets` and intstead use the ones in snarkVM; therefore, this PR replaces the one filed in leo, and adjusts the `pow` operation for signed integers to internally use a new `Mul::wrapping_mul` method in an intermediate operation that should be allowed to overflow.
In addition, the signed `pow` tests are adjusted and extended so that the bug can actually be triggered (which does happen without https://github.com/AleoHQ/snarkVM/pull/103/commits/556073c21da6afe7e97eb5a60e94227e5309dbf6). Some of them are also un-ignored.
Supersedes https://github.com/AleoHQ/leo/pull/762.
Fixes https://github.com/AleoHQ/leo/issues/738.

Fix leo#738

---

objects/src/traits/storage.rs

Two small tweaks:
- `Storage::in_memory` method is changed into a `Storage::IN_MEMORY` const
- `Storage::destroy` is removed - unused, the `Drop` impl is utilized (and better suited) in both `RocksDb` and `MemDb` impls

Adjust the Storage trait

---

dpc/src/base_dpc/inner_circuit/inner_circuit_gadget.rs
dpc/src/base_dpc/record/record_serializer.rs
gadgets/src/algorithms/crh/pedersen.rs
gadgets/src/algorithms/encoding/elligator2.rs
gadgets/src/algorithms/prf/blake2s.rs
gadgets/src/traits/utilities/boolean.rs
nonnative/src/allocated_nonnative_field_mul_result_var.rs
nonnative/src/allocated_nonnative_field_var.rs

This PR is the result of a `cargo clippy --workspace --all-targets` pass, omitting `clippy::upper_case_acronyms` (there are plenty of them and it's a question of whether the names should change or if they should be ignored) and the `storage` crate, which should soon be removable.

Fix 1.51 clippy lints

---

marlin/src/marlin/tests.rs
polycommit/src/sonic_pc/data_structures.rs

This PR fixes the Sonic tests in the new Marlin model by implementing the ToContraintField for the Sonic `VeriiferKey`.

Fix Sonic test compilation in Marlin

---

marlin/src/fiat_shamir/fiat_shamir_algebraic_sponge_gadget.rs
marlin/src/fiat_shamir/fiat_shamir_chacha.rs
nonnative/src/allocated_nonnative_field_var.rs
polycommit/src/lib.rs

This PR adds two additional tests from the the reference implementation - a native chacha rng test and a poseidon sponge gadget test.

Add additional FS RNG tests

---

curves/src/lib.rs
curves/src/sw6/g1.rs
curves/src/sw6/g2.rs
curves/src/sw6/parameters.rs
curves/src/sw6/tests.rs
gadgets/src/traits/utilities/boolean.rs

There are some clippy lints that are reported by GitHub Actions under PRs; they seem to be ones that the `--all-features` option (in addition to the usual `cargo clippy --workspace --all-targets`) can detect.

clippy: fix --all-features lints

---

algorithms/src/merkle_tree/merkle_tree.rs
algorithms/src/merkle_tree/tests.rs
gadgets/src/algorithms/merkle_tree/tests.rs
objects/src/pedersen_merkle_tree.rs
posw/src/circuit.rs
storage/src/ledger.rs
storage/src/objects/dpc_state.rs
storage/src/objects/ledger_scheme.rs

This PR dramatically reduces the time needed to grow the `MerkleTree` object, allowing block syncing in snarkOS to happen in a reasonable time frame. Only when the new leaves share nearly no ancestors a large portion of the tree needs to be rebuilt, otherwise a lot of the pre-exsting hashes can be reused.
The results of this change were validated by using both `MerkleTree::{new, rebuild}` when synchronizing blocks and comparing the trees; no issues were found for the first few thousand blocks taken from the testnet. snarkOS tests also pass with `MerkleTree::rebuild` implicitly being used in tests (when blocks are committed).
In addition, memory use in `MerkleTree::new` is reduced by using an `ExactSizeIterator` instead of a slice for the `leaves` argument.
A snarkOS-side PR will follow …

Speed up merkle tree growth

---

dpc/src/base_dpc/mod.rs

This is needed in order to be able to run `base_dpc` tests outside of their crate, so that `storage` and `testing` crates can be removed.
I'd bundle this change with the removal, but it needs to be a part of a new snarkVM release in order for the integration test crate to work (it must use released dependencies).

Make TransactionKernel members public

---

gadgets/src/traits/utilities/int/int_impl.rs
gadgets/src/traits/utilities/integer.rs
gadgets/src/traits/utilities/uint/arithmetic/add.rs
gadgets/src/traits/utilities/uint/macros.rs
gadgets/src/traits/utilities/uint/uint128.rs
gadgets/src/traits/utilities/uint/unsigned_integer.rs

This PR makes it possible to remove Leo's `IntegerTrait` by extending `Integer` with `get_bits` and `get_value` methods, and also adjusts the unsigned integer error types so they are all aligned. The Leo-side counterpart to this PR is https://github.com/AleoHQ/leo/pull/796.

Align the Integer gadget with leo's IntegerTrait

---

gadgets/src/traits/utilities/bits/adder.rs
gadgets/src/traits/utilities/boolean.rs
gadgets/src/traits/utilities/int/relational/cmp.rs
gadgets/src/traits/utilities/uint/bits/xor.rs
gadgets/src/traits/utilities/uint/relational/cmp.rs

Utilizing common traits as much as possible is preferable in terms of keeping the APIs aligned and cargo docs being able to provide more references to trait implementors.

Use the Xor trait for AllocatedBit and Boolean

---

.circleci/config.yml
utilities/src/bytes.rs

This simplifies the implementations and extends them to arrays with lengths greater than `32`.
Requires [Rust 1.51](https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#const-generics-mvp), so the first commit updates the CI image.

Use const generics to implement byte utilities for arrays

---

Cargo.lock
Cargo.toml
algorithms/src/merkle_tree/merkle_path.rs
algorithms/src/merkle_tree/merkle_tree.rs
algorithms/src/merkle_tree/tests.rs
dpc/src/base_dpc/inner_circuit/inner_circuit.rs
dpc/src/base_dpc/inner_circuit/inner_circuit_verifier_input.rs
dpc/src/base_dpc/mod.rs
dpc/src/base_dpc/outer_circuit/outer_circuit.rs
dpc/src/traits/dpc.rs
gadgets/src/algorithms/merkle_tree/tests.rs
objects/src/pedersen_merkle_tree.rs
objects/src/traits/ledger.rs
parameters/examples/inner_snark.rs
parameters/examples/outer_snark.rs
posw/src/circuit.rs

This will allow us to go lock free for MerkleTree storage for what appears to be very low cost.
This PR also includes `Arc` wrapping for parameters to avoid cloning cost.
This PR includes a version bump for `v0.3.0`. Semver minor bump due to API change in rebuild. It's particularly necessary since previous callers will not get a compiler error for input types, but the return type has changed from nothing to a new struct.
No change in performance observed from this change. See graphs:
Before:
After:
Using 100 block test chain.

Make rebuild return a new MerkleTree for better synchronization logic

---

gadgets/src/algorithms/snark/groth16.rs
gadgets/src/algorithms/snark/tests.rs
marlin/Cargo.toml
marlin/benches/marlin.rs
marlin/src/constraints/snark.rs
marlin/src/constraints/verifier.rs
marlin/src/marlin/marlin.rs

This PR implements additional tests for the snark verification gadgets (groth16, gm17, and marlin) that enforce the fixed size of the gadgets. This will allow us to determine if any underlying components are needlessly changed in future iterations. 
Additionally, new benchmarks for Marlin have been added (universal setup, circuit specific setup, verification, and verification gadget).

Snark verification gadget constraint size tests and Marlin benchmarks

---

Cargo.lock
Cargo.toml
r1cs/src/linear_combination.rs

This PR fixes build-time nondeterminism in `UInt::addmany` through `LinearCombination::add_assign`. Issue was noticed during upgrade from rust 1.51.0 -> 1.52.0, where
[rust 18e44a1b](https://github.com/rust-lang/rust/commit/18e44a1be4d8aecf41d0b904d63f6c72f51d6b0d)
[rust 7d078cfb9](https://github.com/rust-lang/rust/commit/7d078cfb94fa75e5dee699535f3f9781d3a1d47d)
changed internals of `binary_search_by` leading to a change in emitted R1CS. `binary_search_by` doesn't guarantee stability if the items being sorted are not unique, and the excess appending of duplicates this PR fixes removes the issue encountered from changing internals of rust.
*warning* This PR will change emitted R1CS from that of rust `1.51.0, `1.52.0`, and all other versions of rust.

Fix LinearCombination build-time nondeterminism

---

Cargo.lock
algorithms/Cargo.toml
algorithms/benches/crh/bowe_pedersen.rs
algorithms/src/crh/bowe_hopwood_pedersen.rs
algorithms/src/crh/bowe_hopwood_pedersen_compressed.rs
algorithms/src/crh/bowe_hopwood_pedersen_parameters.rs
algorithms/src/crh/mod.rs
algorithms/src/merkle_tree/tests.rs
wasm/Cargo.toml

Optimize Bowe Hopwood Pedersen hashing function
* Removed use of concurrency since it was hurting (bad use case)
* Removed 2 heap allocations (now zero)
* Enforced single copy of input only
* Created lookup table for bit lookups
* Use a larger (I think most optimally 24-bit lookup table) so we can do less/no bit arithmetic
* Note that since we usually do 8 windows, that would take 128 MB of static/on-load-init memory which is kinda big and probably costly to make at runtime. Definitely costly to store in memory.
* Create a specialized variant that requires input to be prepadded for zero-copy
Note that shrinking the stack buffer isn't listed since this aught not to be an expensive allocation (its not heap, just zeroing), and actual testing yielded nothing of significance.
* Hash speed is …

Optimize Bowe Hopwood Pedersen Hash

---

algorithms/benches/crh/bowe_pedersen.rs
algorithms/src/merkle_tree/merkle_tree.rs
algorithms/src/merkle_tree/tests.rs
algorithms/src/traits/commitment.rs
algorithms/src/traits/crh.rs
algorithms/src/traits/merkle_tree.rs
gadgets/src/algorithms/merkle_tree/tests.rs
objects/src/pedersen_merkle_tree.rs
objects/src/traits/transaction.rs
posw/src/circuit.rs
utilities/src/bytes.rs

This PR parallelizes merkle tree build and part of rebuild (only leaf hashing).
Saw a 4x improvement in tree build speed (800ms -> 200ms locally on benchmark). Subjectively, snarkOS loads instantly and syncs quite quickly, during CPU-bound bits.
Upper tree rebuild was not parallelized because A. more complex logic and B. far less hash iterations per rebuild than fresh building.
NOTE: This is a *breaking* change! This requires a minor version update to snarkVM, not a patch.

Parallelize Merkle Tree Build & Rebuild

---

dpc/Cargo.toml
parameters/src/macros.rs

While `snarkos-toolkit` tests pass, the WASM ones failed; I think I've found the last missing bit - with these changes and snarkOS having its snarkVM dependencies changed to local paths, `cargo test --target wasm32-unknown-unknown --no-run` in `snarkos-toolkit` compiles for me.

Make snarkos-toolkit WASM tests compile

---

marlin/src/constraints/verifier.rs
marlin/src/marlin/marlin.rs

Per Slack channel communication with @raychu86, the Marlin verifier gadget fails when there are two inputs, as evidenced by the two failing tests in our [bug/marlin-verification-inputs](https://github.com/AleoHQ/snarkVM/commit/aa7acdd2ad6e1f9d6a734e3e291c2ebe1a8b2006) branch.
An investigation shows that the problem comes from here:
When input has 2 elements [a, b], Marlin pads it to 4 [1, a, b, 0].
- The prover/verifier in the non-constraint world: push [1, a, b, 0] to the sponge
- The verifier gadget in the constraint world: push [1, a, b] to the sponge (ignoring the zero-padding), so there is inconsistency
Therefore, since the sponge is different, all the challenges are different, and the verifier gadget rejects the proof.
After the changes, the code passes the two tests in the …

Fix the Marlin verifier gadget with more than one input

---

marlin/src/constraints/verifier.rs
marlin/src/constraints/verifier_key/circuit_verifier_key.rs
marlin/src/constraints/verifier_key/prepared_circuit_verifier_key.rs
polycommit/src/marlin_pc/gadgets/verifier_key/prepared_verifier_key.rs

First thanks to @raychu86 for discovering this issue. This PR is made to the `bug/marlin-verification-inputs` branch, as there is more to do before merging to `master`.
When Marlin’s constraint gadget prepares the key, it uses a trick to compute a hash of `CommitmentVar<F>` in the native world; this trick breaks the wall between the constraint world and the native world.
This trick is used at that time because arkworks-rs did not have `ToConstraintField` widely implemented in the native world. So, that was the only way to do `to_constraint_elements`. Soon after that arkworks-rs has a wide implementation of `ToConstraintField` for all SW and TE curve points and snarkVM, but we haven't updated these implementations.
This trick would work fine unless the R1CS has another optimization… Recall …

Fix Marlin gadget's risky verifying key preparation

---

marlin/src/ahp/ahp.rs
marlin/src/ahp/verifier/verifier.rs
marlin/src/constraints/ahp.rs
marlin/src/marlin/marlin.rs
polycommit/src/lib.rs
polycommit/src/marlin_pc/gadgets/marlin_kzg10.rs
polycommit/src/marlin_pc/gadgets/proof/batch_lc_proof.rs
polycommit/src/marlin_pc/mod.rs
polycommit/src/sonic_pc/mod.rs

This PR fixes the Marlin verifier. I will push the `bug/marlin-verification-inputs` first. Then, I will push to `feat/testnet2-dpc` in a separate PR, given that there are conflicts that GitHub cannot automatically merge, 
The fix consists of two parts:
- In the Marlin verifier gadgets, sort the points by names instead of values. 
- In the Marlin prover, outputs the proofs' evaluations in the order of point names rather than point values.
The tests in poly-commit and marlin all pass. 
This closes #210.

Fix the Marlin verifier

---

curves/src/bls12_377/fq.rs
fields/src/fp_256.rs
fields/src/fp_320.rs
fields/src/fp_384.rs
fields/src/fp_768.rs
fields/src/fp_832.rs
fields/src/traits/mod.rs
fields/src/traits/poseidon_mds_field.rs
marlin/src/constraints/ahp.rs
marlin/src/constraints/snark.rs
marlin/src/constraints/verifier.rs
marlin/src/constraints/verifier_key/circuit_verifier_key.rs
marlin/src/constraints/verifier_key/prepared_circuit_verifier_key.rs
marlin/src/fiat_shamir/fiat_shamir_algebraic_sponge_gadget.rs
marlin/src/fiat_shamir/fiat_shamir_poseidon_sponge.rs
marlin/src/fiat_shamir/fiat_shamir_poseidon_sponge_gadget.rs

Previously we hardcore a set of parameters for the Poseidon sponge. Today such parameters have more standardized ways of generation, which this PR leverages. (In other words, although prior parameters are not insecure, they are not the best practice today.)
It has never been done in arkworks-rs to have a formal treatment of Poseidon sponge parameters since each curve has its own requirements. This PR makes the first attempts, by explicitly labeling fields with configured MDS matrices and Poseidon parameters.
The update may later be synced into `arkworks-rs`.
It passes the test with respect to `marlin`.
Nope. This is part of a follow-up to the Slack discussion.
The PR was based on the `master` branch instead of `feat/testnet2-dpc` since this change is considerably large (and …

Standardizing the treatment of Poseidon Sponge

---

marlin/src/constraints/snark.rs

It appears that the new Poseidon infrastructure causes a compilation error in the feat/testnet2-dpc branch. This PR fixes it. 
Passes the test in snarkvm-marlin. Based on CircleCI, this is where it fails.
#220 
@howardwu

Fix the compilation error in the latest feat/testnet2-dpc

---

gadgets/src/algorithms/signature/group.rs
gadgets/src/algorithms/signature/tests.rs

There was a minor issue with the signature verification check of the `GroupEncryptionGadget`, where the message length was not included in the Poseidon gadget hash input. 
Tests have been added to check that the signature verification of the `GroupEncryptionGadget` is correct.

Fix `GroupEncryptionGadget` Signature Verification

---

algorithms/benches/signature/schnorr.rs
algorithms/src/signature/group.rs
algorithms/src/signature/schnorr.rs
algorithms/src/signature/schnorr_parameters.rs
algorithms/src/signature/tests.rs
algorithms/src/traits/signature.rs
dpc/src/errors/record.rs
dpc/src/testnet1/inner_circuit/inner_circuit_gadget.rs
dpc/src/testnet1/instantiated.rs
dpc/src/testnet1/mod.rs
dpc/src/testnet1/record/record.rs
dpc/src/testnet1/transaction/kernel.rs
dpc/src/testnet2/inner_circuit/inner_circuit_gadget.rs
dpc/src/testnet2/instantiated.rs
dpc/src/testnet2/mod.rs
dpc/src/testnet2/record/record.rs
dpc/src/testnet2/transaction/kernel.rs
dpc/src/traits/dpc_components.rs
gadgets/src/algorithms/signature/group.rs
gadgets/src/algorithms/signature/schnorr.rs
gadgets/src/algorithms/signature/tests.rs
gadgets/src/traits/algorithms/signature.rs

- Updates Schnorr native and circuit verifier challenge with public key, removing the salt.
- Updates Schnorr native and circuit randomization scheme.
- Adds `CryptoRng` to Signature scheme traits.
This implementation of Schnorr constructs a signature with a `verifier_challenge` defined as:
```
verifier_challenge := ToScalarField( H( prover_commitment || public_key || message_length || message ))
```
As part of this, the former `salt` has been removed. In addition, by introducing the public key to the hash, this requires rearchitecting signature randomization. Previously we employed randomization as follows:
```
[G] := {0, 1}*
private_key := {0, 1}*
[public_key] := private_key * [G]
message := "Hello World"
(prover_response, verifier_challenge) := Sign(private_key, message)
randomizer := …
```

Updates Schnorr native and circuit verifier challenge with public key, removing salt

---

algorithms/src/commitment/pedersen.rs
algorithms/src/commitment/pedersen_compressed.rs
algorithms/src/crh/bowe_hopwood_pedersen.rs
algorithms/src/crh/bowe_hopwood_pedersen_compressed.rs
algorithms/src/crh/pedersen.rs
algorithms/src/crh/pedersen_compressed.rs
gadgets/src/algorithms/commitment/pedersen.rs
gadgets/src/algorithms/commitment/tests.rs
gadgets/src/algorithms/crh/bowe_hopwood_pedersen.rs
gadgets/src/algorithms/crh/pedersen.rs
gadgets/src/algorithms/encryption/group.rs
gadgets/src/curves/templates/bls12/affine.rs
gadgets/src/curves/templates/twisted_edwards/mod.rs
gadgets/src/traits/curves/group.rs

This PR fixes the Merkle tree gadget failure in testnet2, which consists of two parts:
- in the native world, let CRH defined on the projective curve outputs the hash as an affine curve element.
- in the constraint world, apply the corresponding changes.
The change in the constraint world is slightly complicated, as previously the gadgets use `GroupGadget<G, F>` where `G` is always a projective curve, and therefore it implements only `AllocGadget<G, F>` but not `AllocGadget<G::Affine, F>` which we need. 
Therefore, a new trait is introduced to reflect this need. 
```
pub trait CurveGadget<G: ProjectiveCurve, F: Field>: GroupGadget<G, F> + AllocGadget<G::Affine, F> {}
```
(open to suggestions for names for `CurveGadget`)
The requirement `AllocGadget<G::Affine, F>` cannot be added to the …

Fix the Merkle tree inconsistency issue

---

gadgets/src/curves/bls12_377.rs
gadgets/src/curves/edwards_bls12.rs
gadgets/src/curves/edwards_bw6.rs
gadgets/src/curves/templates/bls12/affine.rs
gadgets/src/curves/templates/twisted_edwards/mod.rs

This PR is quite minor as it simply implements the `is_eq` for the `GroupGadget`s. The underlying `FieldGadget`s should already have the `is_eq` implementations.
Tests have been added for each `GroupGadget` instantiation.

Implement `is_eq` for group gadgets

---

gadgets/src/algorithms/signature/schnorr.rs

Very minor changes in this PR, which simply implements the `is_eq` function for `SchnorrPublicKeyGadget` and `SchnorrSignatureGadget`. 
This is needed to support the `is_eq` functionality of Aleo addresses in the gadget world.

Implement `is_eq` for Schnorr gadgets

---

gadgets/src/integers/int/arithmetic/div.rs

This is to fix the bug caught by fuzzing in Leo: https://github.com/AleoHQ/leo/issues/1170
I personally consider it a minor bug, since when this happens, it should either be Rust panicking or Leo showing an error message. 
This PR does the latter instead of the former, as it may confuse the users and provide insufficient debug information.
A similar test appears in the unsigned integer part. So this should work fine. I will wait for the CI.
https://github.com/AleoHQ/leo/issues/1170

Gracefully return an error message upon division by zero for signed integers

---

.integration/tests/dpc_testnet1.rs
dpc/src/testnet1/dpc.rs
dpc/src/testnet1/outer_circuit/outer_circuit_gadget.rs
dpc/src/testnet1/program/noop_program.rs
dpc/src/testnet2/outer_circuit/outer_circuit_gadget.rs

This PR will be into #279. It replaces the testnet1's calls to Poseidon from the byte manner to the field-element manner.
Expect the integration tests would fail due to the need to resample parameters and changing constraint counts.
Let us wait for the CI.
#279

Use Poseidon for Program/Inner Circuit ID in the field-element way

---

.circleci/config.yml

The circle-ci "integration-testnet2" job was running testnet 1 integration tests.

Run testnet 2 integration tests on CI 

---

algorithms/src/snark/gm17/mod.rs
algorithms/src/snark/groth16/mod.rs

This PR makes the deserialization buffer handling in `Proof::read` for snarks faster (fewer allocations) and more idiomatic.
This was detected when profiling the snarkOS storage validator, as the `Proof::read` function was called a lot of times.

Reduce the number of allocations used to deserialize snark proofs

---

utilities/src/bytes.rs

This PR greatly shortens the `bytes` module in `snarkvm-utilities` by utilizing macros to implement `FromBytes` and `ToBytes`.

Use more macros in the bytes module

---

algorithms/src/encryption/ecies_poseidon.rs
algorithms/src/encryption/group.rs
algorithms/src/encryption/mod.rs
algorithms/src/encryption/tests.rs
algorithms/src/traits/encryption.rs
dpc/src/circuits/inner_circuit_gadget.rs
dpc/src/record/encrypted.rs
gadgets/src/algorithms/encryption/ecies_poseidon.rs
gadgets/src/algorithms/encryption/group.rs
gadgets/src/algorithms/encryption/mod.rs
gadgets/src/algorithms/encryption/tests.rs
gadgets/src/bits/to_bytes.rs
gadgets/src/traits/algorithms/encryption.rs
gadgets/src/traits/alloc.rs
gadgets/src/traits/eq.rs

This PR supples the ECIES Poseidon encryption, which is likely going to replace group encryption. 
Currently the group encryption has certain challenges: (1) elligator is not performing ideally for a few reasons and (2) it seems to complicate our serialization.
This one supplies an ECIES Poseidon encryption, which is likely to be faster than the group encryption, and can work securely when the same key is also used with Schnorr signatures. 
There is a possibility of using ElGamal hybrid encryption later, which will also be using Poseidon for the symmetric encryption part, and can reuse the code here.
The ECIES Poseidon uses the same tests as used by group encryption.

Add ECIES Poseidon encryption

---

dpc/src/circuits/inner_circuit_gadget.rs
dpc/src/circuits/inner_circuit_verifier_input.rs
dpc/src/circuits/outer_circuit_verifier_input.rs
dpc/src/testnet1/outer_circuit/outer_circuit_gadget.rs
dpc/src/testnet1/program/noop_program_circuit.rs
dpc/src/testnet2/outer_circuit/outer_circuit_gadget.rs
dpc/src/testnet2/program/noop_program_circuit.rs
gadgets/src/algorithms/commitment/bhp.rs
gadgets/src/algorithms/commitment/bhp_compressed.rs
gadgets/src/algorithms/commitment/blake2s.rs
gadgets/src/algorithms/commitment/pedersen.rs
gadgets/src/algorithms/commitment/pedersen_compressed.rs
gadgets/src/algorithms/commitment/tests.rs
gadgets/src/algorithms/commitment_tree/tests.rs
gadgets/src/algorithms/crh/bhp.rs
gadgets/src/algorithms/crh/bhp_compressed.rs
gadgets/src/algorithms/crh/pedersen.rs
gadgets/src/algorithms/crh/pedersen_compressed.rs
gadgets/src/algorithms/crh/tests.rs
gadgets/src/algorithms/crypto_hash/poseidon.rs
gadgets/src/algorithms/encryption/ecies_poseidon.rs
gadgets/src/algorithms/encryption/group.rs
gadgets/src/algorithms/encryption/tests.rs
gadgets/src/algorithms/merkle_tree/tests.rs
gadgets/src/algorithms/signature/schnorr.rs
gadgets/src/algorithms/signature/tests.rs
posw/src/circuit.rs

This PR makes two changes:
- force all the crypto primitives parameters to be allocated only through `alloc_constant`, and `alloc`/`alloc_input` is now "unimplemented" and will cause a panic
- update the DPC to allocate the cryptographic primitive gadgets using `alloc_constant`
- remove the serialization of cryptographic primitive parameters (which at this moment is empty).
Some tests have been executed in `gadgets` and related dirs.

Use `alloc_constant` for parameters for crypto primitives

---

CONTRIBUTING.md
README.md

`snarkVM` is central to the entire Aleo ecosystem. The effects of bugs or even small changes to this codebase ripple outward from here and have unintended consequences, so it's imperative that software engineering best practices are followed to match the mathematical and cryptographic precision required by the VM.
The changes proposed are a mild set of quick and easily-enforceable idioms that EQ has found to improve not only the quality of the code, but the quality of experience of _working with_ the code.
Note: Here's the ink to [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to draw it out of the `.md` file in the changeset

`CONTRIBUTING.md` basics section

---

dpc/src/block/transactions.rs

In starting on an early consensus module, I stumbled across a function that didn't get updated when we removed the requirement for unique transaction memos. This PR resolves that issue by removing this enforcement.

fix(Transactions::conflict): Removes unique memos requirement

---

.github/ISSUE_TEMPLATE/feature.md

This commit removes one set of `../`s from the issue template so that it links to `AleoHQ/snarkVM/CONTRIBUTING.md` instead of `AleoHQ/CONTRIBUTING.md`, a 404.

fix(issue-template): change to non-404 link

---

dpc/src/parameters/common.rs
dpc/src/parameters/mod.rs
dpc/src/parameters/testnet1.rs
dpc/src/parameters/testnet2.rs

This PR deduplicates 2 testnet-specific `dpc` macros, as suggested in https://github.com/AleoHQ/snarkVM/pull/320#discussion_r678908634.

Deduplicate testnet-dpecific dpc macros

---

.integration/tests/dpc_testnet1.rs
.integration/tests/dpc_testnet2.rs
algorithms/src/merkle_tree/mod.rs
algorithms/src/merkle_tree/tests.rs
dpc/src/errors/ledger.rs
dpc/src/parameters/testnet1.rs
dpc/src/parameters/testnet2.rs
dpc/src/traits/parameters.rs
ledger/Cargo.toml
ledger/src/block/block_header.rs
ledger/src/errors/storage.rs
ledger/src/ledger/ledger.rs
ledger/src/ledger/mod.rs
ledger/src/ledger/tests.rs
parameters/examples/genesis.rs

This PR adds parameters for a record serial number tree, which after discussion is necessary for light client support. In addition, to enable consensus on the genesis block, we set the initialized ledger's block height to a convention of 1.
- Adds record serial number tree parameters
- Enforces a newly-initialized ledger has block height of 1
- Adds a basic convention for a genesis block header

Adds record serial number tree parameters, enforce new ledger block height of 1

---

Cargo.lock
algorithms/Cargo.toml
algorithms/src/crh/bhp.rs
algorithms/src/crh/pedersen.rs

No more gd `bitvec`.
```
Before
-------
Pedersen CRH setup      time:   [635.04 us 636.57 us 638.71 us]                               
Found 3 outliers among 50 measurements (6.00%)
1 (2.00%) high mild
2 (4.00%) high severe
Pedersen CRH hash       time:   [62.865 us 62.992 us 63.120 us]                             
Found 4 outliers among 50 measurements (8.00%)
3 (6.00%) high mild
1 (2.00%) high severe
After
------
Pedersen CRH setup      time:   [636.88 us 639.05 us 642.13 us]                               
change: [-0.2128% +0.5658% +1.5633%] (p = 0.24 > 0.05)
No change in performance detected.
Found 2 outliers among 50 measurements (4.00%)
1 (2.00%) high mild
1 (2.00%) high severe
Pedersen CRH hash       time:   [63.615 us 63.723 us 63.845 us]                             
change: …
```

No more gd `bitvec`

---

dpc/examples/account.rs
dpc/src/errors/dpc.rs
dpc/src/errors/mod.rs
dpc/src/program/noop_program.rs
dpc/src/record/record.rs
dpc/src/traits/program.rs
ledger/src/errors/ledger.rs
ledger/src/errors/mod.rs
parameters/examples/genesis.rs

Improves `Program` ergonomics
- Arcs the usage of program circuit tree
- Allows `Record` to take dynamic program reference
- Adds an account creation example in the DPC crate
- Moves `LedgerError` to `snarkvm_ledger` (missed this migration earlier)

Improves `Program` ergonomics

---

.integration/tests/dpc_testnet1.rs
.integration/tests/dpc_testnet2.rs
dpc/src/circuits/inner_circuit.rs
dpc/src/circuits/inner_circuit_gadget.rs
dpc/src/circuits/inner_circuit_verifier_input.rs
dpc/src/circuits/outer_circuit.rs
dpc/src/circuits/outer_circuit_gadget.rs
dpc/src/circuits/outer_circuit_verifier_input.rs
dpc/src/dpc.rs
dpc/src/parameters/testnet1.rs
dpc/src/parameters/testnet2.rs
dpc/src/program/program.rs
dpc/src/traits/parameters.rs
dpc/src/transaction/local_data.rs
dpc/src/transaction/transaction.rs

This is a mild PR to reduce the cost of deriving the inner circuit ID by making it static, no circuit changes in this PR. This PR will allow `snarkOS` to derive the inner circuit ID in a network-agnostic manner.
- Adds a static `Parameters::inner_circuit_id()` to prevent recomputing unnecessarily
- Renames `Parameters::InnerCircuitIDCRHDigest` to `Parameters::InnerCircuitID`
- Renames `Parameters::LocalDataDigest` to `Parameters::LocalDataRoot`
- Updates `DPC::execute()` and `DPC::verify()` to use static `Parameters::inner_circuit_id()`
- Adds debug-only safety checks that loaded and saved inner circuit ID match
- Remark: A desirable goal is to remove the inner and outer circuit parameter variables inside the DPC struct, as Parameters already has static getter methods for these. However …

Adds a static `Parameters::inner_circuit_id()` to prevent recomputing unnecessarily

---

algorithms/src/crh/bowe_hopwood_pedersen.rs
algorithms/src/crh/bowe_hopwood_pedersen_compressed.rs
algorithms/src/crh/bowe_hopwood_pedersen_parameters.rs

After the snarkOS update to `0.7.5` (and `0.7.6`), the storage loading process became significantly slower: https://github.com/AleoHQ/snarkOS/issues/1003. This was caused by the fact that due to aggressive parallelization, the value of `base_lookup` was initialized (or rather an attempt to initialize it was made) **many** times instead of just once.
The results of this PR for the storage loading process in snarkOS are as follows:
```
before: 107781ms
after:  4926ms
```

Fix a MerkleTree::new slowdown

---

algorithms/src/merkle_tree/tests.rs
gadgets/src/algorithms/merkle_tree/tests.rs
ledger/src/posw/mod.rs
ledger/tests/mod.rs

This PR was motivated by https://github.com/AleoHQ/snarkVM/issues/280, where a test was using technically invalid test values (as there were non-unique Merkle tree leaves), which initially led to some misleading results. While that specific test is going away when https://github.com/AleoHQ/snarkVM/pull/298 gets merged, there are still some tests that are using dummy values as inputs; with this PR, randomized values for Merkle tree leaves are used instead, improving the quality of the affected tests.
note: this PR was done against the upcoming `testnet2` branch, in order to avoid any conflicts with it.

Randomized Merkle tree leaves in tests

---

dpc/src/program/noop_circuit.rs
dpc/src/traits/program.rs

This adds a required function `as_any` to the `ProgramPrivateVariables` trait, to facilitate casting casting the `private: &dyn ProgramPrivateVariables<C>` variable into usable structs without having to use unsafe transmutes.

Implement casting for ProgramPrivateVariables trait

---

.integration/tests/dpc_testnet1.rs
.integration/tests/dpc_testnet2.rs
algorithms/src/errors/merkle.rs
algorithms/src/traits/encryption.rs
dpc/src/account/address.rs
dpc/src/circuits/outer_circuit_gadget.rs
dpc/src/dpc.rs
dpc/src/errors/dpc.rs
dpc/src/errors/record.rs
dpc/src/parameters/testnet1.rs
dpc/src/parameters/testnet2.rs
dpc/src/program/executable.rs
dpc/src/program/execution.rs
dpc/src/program/mod.rs
dpc/src/program/noop_circuit.rs
dpc/src/program/noop_program.rs
dpc/src/program/program.rs
dpc/src/program/program_circuit_tree.rs
dpc/src/program/public_variables.rs
dpc/src/record/encrypted.rs
dpc/src/record/payload.rs
dpc/src/record/record.rs
dpc/src/record/tests.rs
dpc/src/traits/dpc.rs
dpc/src/traits/parameters.rs
dpc/src/traits/program.rs
dpc/src/traits/record.rs
parameters/examples/genesis.rs
parameters/examples/noop_program_snark.rs
parameters/examples/outer_snark.rs

Adds enhancements for the DPC program model.
- Adds `Copy` trait to `Address` struct
- Removes `position` from `Record` struct (it is never used)
- Adds `Record::new_noop_input()` and `Record::new_noop_output()`
- Adds `Record::new_input()` and `Record::new_output()`
- Includes #343 
- Reverses program public variables declaration to match allocation order
- Changes program circuits to be referenced from `circuit_id` instead of `circuit_index` (error-prone convention)
- Adds `Parameters::noop_circuit_id()` only for use in `load()` methods
- Adds helper method `fn program_circuit_id(verifying_key: &<Self::ProgramSNARK as SNARK>::VerifyingKey) -> Result<Self::ProgramCircuitID>` into `Parameters`
- Renames `Parameters::program_id_crh()` to `Parameters::program_circuit_id_crh()`
- Renames …

Adds enhancements for the DPC program model

---

dpc/src/account/account.rs
dpc/src/account/tests.rs
dpc/src/traits/account.rs

I am currently refactoring the aleo sdk to be compatible with the testnet2 branch of snarkVM.  
One desired feature of the sdk is to import an account from a private key - example: `Account::from_private_key()`.  
The sdk uses the `Account<C: Parameters>` struct in snarkVM which does not provide this functionality.  
Rather than re-implement the `Account` struct in aleo sdk this PR adds the desired method in snarkVM.
* add `Account::from_private_key()` method to `AccountScheme` trait.
* implement `Account::from_private_key()` method for generic `Account<C: Parameters>` struct.
* add test for `Account::from_private_key()` in account tests.

implement account from_private_key

---

Cargo.lock
dpc/Cargo.toml
dpc/src/dpc.rs
dpc/src/traits/dpc.rs

While investigating block import time spikes in snarkOS, profiling showed that `DPCScheme::verify_transactions` accounted for a significant part of that process; I was wondering if it could be improved and noticed that it was run sequentially, while it could be parallelized - it just required some tweaks to traits. I was being conservative and only added `Sync` (and sometimes `Send`) where the compiler required it.

Parallel transaction verification

---

dpc/src/testnet1/inner_circuit/inner_circuit.rs
dpc/src/testnet1/inner_circuit/inner_circuit_verifier_input.rs
dpc/src/testnet1/mod.rs
dpc/src/testnet1/outer_circuit/outer_circuit.rs
dpc/src/testnet2/inner_circuit/inner_circuit.rs
dpc/src/testnet2/inner_circuit/inner_circuit_verifier_input.rs
dpc/src/testnet2/mod.rs
dpc/src/testnet2/outer_circuit/outer_circuit.rs
parameters/examples/inner_snark.rs
parameters/examples/outer_snark.rs
parameters/examples/testnet2_inner_snark.rs
parameters/examples/testnet2_outer_snark.rs

This PR is a result of profiling done in snarkOS - the `SystemParameters` object is relatively expensive to clone, so wrapping it in an `Arc` can result in a noticeable performance improvement.

Arced system parameters

---

marlin/src/marlin/errors.rs
marlin/src/parameters.rs
marlin/src/snark.rs

Fixes inconsistency caused by some manual mappings.

Consistently map terminated MarlinError::Terminated into SnarkError::Terminated

---

algorithms/src/merkle_tree/merkle_path.rs
algorithms/src/merkle_tree/merkle_tree.rs
algorithms/src/snark/groth16/mod.rs
fields/src/to_field_vec.rs
utilities/src/bytes.rs

snarkOS profiling results indicate that allocations are non-negligible, especially while fast-forwarding blocks; this PR targets allocations in some hot functions.

Reduce the number of allocations in some hot functions

---

dpc/src/ledger/ledger.rs
dpc/src/ledger/memory_pool.rs
dpc/src/traits/network.rs

This PR renames `clear_transactions` to `clear_all_transactions` and adds 3 additional functions to the `MemoryPool` - 
1. `remove_transaction`
2. `remove_transactions`
3. `remove_block`

Add additional memory pool functions

---

algorithms/src/merkle_tree/merkle_tree.rs
algorithms/src/merkle_tree/tests.rs
dpc/src/block/header.rs
dpc/src/ledger/ledger_tree.rs
marlin/src/constraints/verifier.rs
marlin/src/marlin/marlin.rs
polycommit/src/marlin_pc/gadgets/marlin_kzg10.rs
polycommit/src/sonic_pc/gadgets/sonic_kzg10.rs

This PR fixes merkle tree rebuilds and updates updates the parallelization of leaf hashing. Additionally an optimization has been added to `LedgerTree`.
A rebuild test has been added to ensure that the tree is being rebuilt correctly.
Quick benchmark of the merkle tree implementations
**Old:**
- 1000 leaves:
- new() - 500 ms
- rebuild() - 508 ms
- 10000 leaves:
- new() - 5768 ms
- rebuild() - 5791 ms
- 100000 leaves:
- new() - 52099 ms (52 seconds)
- rebuild() - 52115 ms (52 seconds)
**New:**
- 1000 leaves:
- new() - 33 ms
- rebuild() - 280 ms
- 10000 leaves:
- new() - 199 ms
- rebuild() - 3667 ms
- 100000 leaves:
- new() - 1724 ms
- rebuild() - 31108 ms (31 seconds)

Fix merkle tree rebuilds

---

dpc/src/block/header.rs
dpc/src/network/testnet1.rs
dpc/src/network/testnet2.rs
dpc/src/traits/network.rs

Adds a block header size constant in `Network` trait
Adds a test for block header size constant in `dpc/src/block/header.rs`.

Adds a block header size constant in `Network` trait

---

.circleci/config.yml

This PR updates the CircleCI Rust images from `1.53.0` to `1.56.1`.

Update the CI rust images

---

eval/src/setup/state.rs

Quick fix that follows #497. 
HashMap has different order in Union vs IndexMap, so bounded recursion tests started to fail on the Leo side. This PR addresses that problem and finalizes HashMap->IndexMap shift.
All tests pass on the Leo side.

Fix IndexMap extend order 

---

eval/src/setup/instruction/core/common/unwrap_args.rs
eval/src/setup/instruction/mod.rs
eval/src/setup/mod.rs
eval/tests/test.rs
ir/src/function.rs
ir/src/header.rs
ir/src/input.rs
ir/src/instruction/array.rs
ir/src/instruction/call.rs
ir/src/instruction/complex.rs
ir/src/instruction/mod.rs
ir/src/instruction/predicate.rs
ir/src/instruction/query.rs
ir/src/program.rs
ir/src/types.rs
ir/src/values/group.rs
ir/src/values/mod.rs

Some anyhow update or change made it so `use anyhow::*;` was importing an anyhow Ok.

fix anyhow result issues by direct imports
