AleoHQ/snarkVM

.circleci/config.yml
=> Update CI dockerfiles

Cargo.lock, Cargo.toml, README.md, snarkvm/cli.rs, snarkvm/commands.rs, snarkvm/errors.rs, snarkvm/lib.rs, snarkvm/main.rs, snarkvm/updater.rs
=> Adds CLI and updates README

dpc/src/base_dpc/mod.rs, models/src/dpc/dpc.rs
=> Removes LedgerScheme::Metadata

algorithms/src/snark/gm17/generator.rs, algorithms/src/snark/gm17/prover.rs, algorithms/src/snark/gm17/r1cs_to_sap.rs, algorithms/src/snark/groth16/generator.rs, algorithms/src/snark/groth16/mod.rs, algorithms/src/snark/groth16/prover.rs, algorithms/src/snark/groth16/r1cs_to_qap.rs, marlin/src/ahp/constraint_systems.rs, marlin/src/ahp/indexer.rs, marlin/src/ahp/prover.rs, models/src/gadgets/curves/fp.rs, models/src/gadgets/curves/fp2.rs, models/src/gadgets/curves/fp6_3over2.rs, models/src/gadgets/r1cs/constraint_counter.rs, models/src/gadgets/r1cs/constraint_system.rs, models/src/gadgets/r1cs/constraint_variable.rs, models/src/gadgets/r1cs/linear_combination.rs, models/src/gadgets/r1cs/mod.rs, models/src/gadgets/r1cs/namespace.rs, models/src/gadgets/r1cs/test_constraint_system.rs, models/src/gadgets/utilities/boolean.rs, polycommit/src/marlin_pc/mod.rs
- Adds `num_public_variables` and` num_private_variables` to ConstraintSystem
- Renames all references of `input` to `public_variable` and `aux` to `private_variable`
- Renames `ConstraintVar` to `ConstraintVariable`
=> Upgrades to the ConstraintSystem

marlin/src/ahp/constraint_systems.rs, marlin/src/ahp/indexer.rs, marlin/src/ahp/mod.rs, marlin/src/ahp/prover.rs, marlin/src/ahp/verifier.rs, marlin/src/data_structures.rs, marlin/src/lib.rs, marlin/src/parameters.rs, marlin/src/snark.rs, polycommit/src/data_structures.rs, polycommit/src/kzg10/mod.rs, polycommit/src/lib.rs, polycommit/src/marlin_pc/mod.rs, polycommit/src/sonic_pc/mod.rs, utilities/src/serialize/mod.rs
Removes unnecessary lifetime parameters in Marlin and polycommit
=> Removes unnecessary lifetime parameters in Marlin and polycommit

Cargo.lock, posw/Cargo.toml, posw/tests/mod.rs
Adds PoSW explicit test for testnet1
=> Adds PoSW explicit test for testnet1

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, wasm/Cargo.toml, wasm/LICENSE.md, wasm/README.md, wasm/src/lib.rs
=> Adds early wasm template

Cargo.lock, posw/Cargo.toml, posw/benches/posw.rs, posw/src/posw.rs
=> Adds benchmarks for PoSW

fields/src/fp_256.rs, fields/src/fp_320.rs, fields/src/fp_384.rs, fields/src/fp_768.rs, fields/src/fp_832.rs, utilities/src/biginteger/macros.rs
Updates Fp Display to human-readable format, Fp Debug to hexadecimal format
=> Updates Fp Display to human-readable format, Fp Debug to hexadecimal format

marlin/src/ahp/indexer/indexer.rs, marlin/src/ahp/prover/prover.rs, marlin/src/marlin/marlin.rs, marlin/src/marlin/tests.rs, polycommit/src/kzg10/mod.rs, polycommit/src/lib.rs, polycommit/src/marlin_pc/mod.rs, polycommit/src/sonic_pc/mod.rs
Refactors polycommit and updates Marlin recursion tests
=> Refactors polycommit and updates Marlin recursion tests

marlin/benches/marlin.rs, marlin/src/marlin/marlin.rs, marlin/src/marlin/tests.rs, marlin/src/parameters.rs, marlin/src/snark.rs, parameters/examples/posw_snark.rs, polycommit/src/kzg10/mod.rs, polycommit/src/lib.rs, polycommit/src/marlin_pc/mod.rs, posw/benches/posw.rs, posw/src/lib.rs
- Implements marlin recursion tests
- Refactors `polycommit` trait and impls to a simpler form
- Simplifies usage of Marlin to `MarlinTestnet1` struct
=> Implements marlin recursion tests

.cargo/config, .circleci/config.yml, Cargo.toml
- Adds noconfig feature flag
- Updates CI docker container
=> Adds `noconfig` feature flag, updates CI docker container

algorithms/src/crh/pedersen.rs
This PR gets a 47% performance increase in PedersenCRH performance.
Another compounding 50% or so is possible through doing some window lookups.
=> Optimize PedersenCRH

dpc/Cargo.toml
=> Add wasm feature to dpc

gadgets/src/fields/fp.rs
* fix `from_boolean()` method for `FpAllocated`
* use `alloc_constant()` in FpGadget conditional select
=> Fixes FpGadget conditional select gadget

.cargo/config
Fix native cpu flag on release
=> Fix native cpu flag on release

.integration/src/storage.rs, dpc/src/errors/mod.rs, dpc/src/errors/record.rs, dpc/src/testnet1/mod.rs, dpc/src/testnet1/record/record.rs, dpc/src/testnet1/record/record_encryption.rs, dpc/src/testnet1/record/tests.rs
Adds serialized string support for records
=> Adds serialized string support for records

Cargo.lock, algorithms/Cargo.toml, algorithms/benches/crh/bowe_pedersen.rs, algorithms/src/crh/bowe_hopwood_pedersen.rs, algorithms/src/crh/bowe_hopwood_pedersen_compressed.rs, algorithms/src/crh/bowe_hopwood_pedersen_parameters.rs, curves/Cargo.toml
For account creation speeds where we run setup but never hash. Also parallelizes setup.
=> Parallelize BH pedersen setup

marlin/src/ahp/verifier/verifier.rs, marlin/src/constraints/ahp.rs, marlin/src/marlin/marlin.rs, polycommit/src/lib.rs, polycommit/src/marlin_pc/gadgets/marlin_kzg10.rs, polycommit/src/marlin_pc/gadgets/proof/batch_lc_proof.rs, polycommit/src/marlin_pc/mod.rs, polycommit/src/sonic_pc/mod.rs
This PR mirrors #222, but it is pushed to `feat/testnet2-dpc`. 
GitHub and my local merge via `git apply -3` seem to have some conflicts, so I merge manually.
Tests in `polycommit` and `marlin` all pass.
This is essentially the same PR as #222, albeit solving the merge conflicts.
It closes #210.
=> Apply the changes that fix the Marlin verifier to `feat/testnet2-dpc`

.gitignore, parameters/src/global/mod.rs, parameters/src/macros.rs, parameters/src/testnet1/mod.rs, parameters/src/testnet2/mod.rs
Add remote param safety check, update parameters to new bucket with additional parameters
=> Add remote param safety check, update parameters to new bucket with additional parameters

.integration/src/ledger.rs, algorithms/src/merkle_tree/merkle_tree.rs
This PR removes the need to pass in all existing commitments to rebuild -- only the length is needed. Didn't alter the storage model in `.integration` since it is being changed in snarkOS.
=> Simplify rebuild

.circleci/config.yml, gadgets/src/integers/int/tests/int128.rs, gadgets/src/integers/uint/tests/uint128.rs, r1cs/src/lib.rs, r1cs/src/test_constraint_checker.rs
This PR supplies a memory-efficient test constraint system, called `TestConstraintChecker`, that does not compute the full paths and does not store constraints, but still preserves the functionality of checking if a constraint system is satisfied.
The code has been beta-tested on a few tests.
We will see if the CI time improves.
=> A memory-efficient constraint system checker for CI

algorithms/src/encoding/field_encoding.rs, algorithms/src/encoding/mod.rs, algorithms/src/encoding/tests.rs, algorithms/src/encryption/ecies_poseidon.rs, algorithms/src/encryption/tests.rs, algorithms/src/traits/encoding.rs, dpc/src/circuits/inner_circuit_gadget.rs, dpc/src/record/encoded.rs, dpc/src/testnet1/parameters.rs, dpc/src/testnet2/parameters.rs, dpc/src/traits/parameters.rs, gadgets/src/algorithms/encoding/field_encoding.rs, gadgets/src/algorithms/encoding/mod.rs, gadgets/src/algorithms/encoding/tests.rs, gadgets/src/algorithms/encryption/ecies_poseidon.rs, gadgets/src/algorithms/encryption/tests.rs, gadgets/src/traits/algorithms/encoding.rs
Simplification of encoding scheme. Intended to be merged into PR #316.
This PR has no functional changes from #316, merely attempts to make the implementation more ergonomic.
=> Simplification of encoding scheme

dpc/src/testnet1/record/record.rs, dpc/src/testnet2/record/record.rs
Fixes #337.
Patch release requested after merge.
=> Publicize record fields

dpc/src/testnet1/record/record.rs, dpc/src/testnet2/record/record.rs
=> Revert "Publicize record fields"

dpc/src/testnet1/record/encrypted.rs, dpc/src/testnet1/record/record.rs
=> Add SN randomness to 'from' for record

dpc/src/testnet1/record/encrypted.rs, dpc/src/testnet1/record/record.rs, dpc/src/testnet2/record/record.rs, dpc/src/traits/record.rs
=> Expose position in testnet1 record

marlin/src/constraints/snark.rs, marlin/src/fiat_shamir/fiat_shamir_chacha.rs, marlin/src/marlin/marlin.rs, marlin/src/marlin/mode.rs
Adds Clone and Debug to Marlin structs
=> Adds Clone and Debug to Marlin structs

dpc/src/dpc.rs
Fixes index error in `DPC::authorize`.
=> Fix index error in DPC::authorize

algorithms/src/crh/pedersen.rs, algorithms/src/crh/poseidon.rs
Found while looking at the prospect of migrating https://github.com/AleoHQ/snarkVM/pull/372 for `testnet2`.
=> Don't allocate when hashing if there is no need for padding

dpc/src/block/header.rs
implements Display trait for BlockHeader ensuring to_string outputs a json string and from_str consumes it
=> feat: impl human readable Display trait for BlockHeader

dpc/src/circuits/tests.rs, dpc/src/transaction/transaction.rs, dpc/src/transition/request.rs, dpc/src/virtual_machine/builder.rs, dpc/src/virtual_machine/operation.rs, dpc/src/virtual_machine/output.rs, dpc/src/virtual_machine/virtual_machine.rs
This PR adds support for declaring events in the transaction builder
=> Add support for declaring events

Cargo.lock, ir/Cargo.toml, ir/src/function.rs, ir/src/header.rs, ir/src/input.rs, ir/src/instruction/array.rs, ir/src/instruction/call.rs, ir/src/instruction/complex.rs, ir/src/instruction/mod.rs, ir/src/instruction/predicate.rs, ir/src/instruction/query.rs, ir/src/program.rs, ir/src/types.rs, ir/src/values/field.rs, ir/src/values/group.rs, ir/src/values/mod.rs, snarkvm/commands.rs, snarkvm/updater.rs
For better ACL2 and machine-readability we need IR to be serializable to different formats. 
Motivation is covered in: https://github.com/AleoHQ/leo/issues/1440
Current tests are expected to pass.
@bendyarm this is how serialization to JSON would look like:
```asm
decl f0: <0>
store &v2, ((v0, v1), (), (), ())
store &v4, (true, false)
retn (true, false)
```
-> 
```json
{
"header":{
"version":{
"major":0,
"minor":7,
"patch":9
},
"main_inputs":[
{
"variable":3,
"name":"a",
"type_":{
"Tuple":[
"Boolean",
"Boolean"
]
}
}
],
"constant_inputs":[
],
"register_inputs":[
{
"variable":0,
"name":"b",
"type_":"Boolean"
},
{
"variable":1,
"name":"c",
"type_":"Boolean"
}
],
"public_states":[],
"private_record_states":[],
"private_leaf_states":[],
"inline_limit":0
},
"functions":[
{ …
```
=> Adds Serde to snarkvm IR

Cargo.lock, eval/Cargo.toml, eval/src/setup/mod.rs, eval/src/setup/state.rs
Described in the issue #496.
Not quite sure how to test this behavior as it was hard to catch it in the first place. Ran multiple tests locally to verify that order is preserved.
> Fix looks super easy, but @d0cd and myself spent hours debugging and tracing it to this point.
=> Fix non-deterministic proofs (in IR)
